project:
  type: book

book:
  title: "The unrecognized role of fidelity in hybrid effectiveness-implementation trials: simulation study and guidance for implementation researchers"
  author: 
    - name: "Diana Trutschel [ORCID: 0000-0002-1727-9736]"
    - name: "Catherine Blatter [ORCID: 0000-0002-4069-7178]"
    - name: "Michael Simon [ORCID: 0000-0003-2349-7219]"
    - name: "Thekla Brunkert [ORCID: 0000-0002-0369-1826]"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - simulation-step-by-step.qmd
    - additional-statistical-info.qmd
    - references.qmd
  url: https://ins-basel.github.io/fidelity-tutorial

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



